services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: football
      POSTGRES_USER: football
      POSTGRES_PASSWORD: football
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U football -d football"]
      interval: 5s
      timeout: 3s
      retries: 20

  ingestion:
    build:
      context: ./ingestion
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: football
      POSTGRES_USER: football
      POSTGRES_PASSWORD: football

      # Football Data API
      FOOTBALL_DATA_TOKEN: ${FOOTBALL_DATA_TOKEN}
      COMPETITION_CODE: ${COMPETITION_CODE:-FL1}
      DATE_FROM: ${DATE_FROM:-}
      DATE_TO: ${DATE_TO:-}
    restart: "no"

volumes:
  pgdata:
